version: "3.9"

services:
  pg:
    image: postgres:16-alpine
    container_name: pg_hw
    environment:
      POSTGRES_USER: hw
      POSTGRES_PASSWORD: hw
      POSTGRES_DB: hw
    # сеть как у хоста, из-за Tailscale с exit-node приходиться мне так делать
    network_mode: host
    volumes:
      - pgdata_hw:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_hw:
